---
title: "The Value of Accepting the Null Hypothesis"
author: "Andy Grogan-Kaylor"
date: "`r Sys.time()`"
output:
  html_document:
    highlight: haddock
    theme: default
  pdf_document: 
    highlight: haddock
    latex_engine: xelatex
subtitle: Important Substantive Cases
institute: University of Michigan
---

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

```

# The Value of Accepting the Null Hypothesis ($H_0$)

```{r}

library(pander) # nice tables

case <- c("Equivalence Testing",
          "Equivalence Testing",
          "Retiring Interventions",
          "Contextual Equivalence",
          "Full Mediation",
          "Theory Simplification")

description <- c("Equivalence Of 2 Treatments Or Interventions",
                 "Equivalence Of 2 Groups On An Outcome",
                 "There Is No Evidence That Intervention X Is Effective",
                 "Equivalence of a Predictor Across Contexts (Moderation)",
                 "$x \\rightarrow y$ Association Is Completely Mediated; No Direct Effect",
                 "Removing An Association From A Theory")

H0 <- c("$\\beta_1 = \\beta_2$",
        "$\\bar{x_1} = \\bar{x_2}$",
        "$\\beta_{intervention} = 0$",
        "$\\beta_{interaction} = 0$",
        "$\\beta_{xmy} \\neq 0$; $\\beta_{xy} = 0$",
        "$\\beta_x = 0$")

example <- c("The effect of Treatment A is indistinguishable from the effect of Treatment B (especially important if one treatment is much more expensive, or time consuming than another).",
             "Men and women are more similar than different *wrt* psychological processes (Hyde).", 
             "Evidence consistently suggests that a particular treatment has near zero effect.",
             "Warm and supportive parenting is equally beneficial across different contexts or countries.",
             "The relationship of the treatment and the outcome is completely mediated by mechanism *m*.",
             "There is no evidence that x is associated with y.")

Bayesdata <- data.frame(case, 
                     description,
                     H0,
                     example)

library(rmarkdown)

save(Bayesdata, file = "accepting-H0.RData")

pander(Bayesdata, split.cells = 10)

# knitr::kable(Bayesdata,
#              col.names = c("Case", 
#                            "Description",
#                            "Null Hypothesis",
#                            "Example"))

```

```{r, echo=FALSE, eval=FALSE}

# | Case | Example |
# |------|---------|
# | Equivalence Testing |

```







